DigiComp:
  FlowSessionLock:
    lockStoreConnection: "flock://%FLOW_PATH_DATA%Temporary/Production/SessionLocks/"
    timeToLive: 300.0
    autoRelease: true
    readOnlyExpressions: {}

Neos:
  Flow:
    http:
      chain:
        preprocess:
          chain:
            lockSession:
              position: "before getSessionCookieFromRequest"
              component: "DigiComp\\FlowSessionLock\\Http\\SessionLockRequestComponent"
