DigiComp:
  FlowSessionLock:
    lockStoreConnection: "flock://%FLOW_PATH_DATA%Temporary/Production/SessionLocks/"
    timeToLive: 300.0
    autoRelease: true
    secondsToWait: 30
    readOnlyExpressions: {}

Neos:
  Flow:
    http:
      middlewares:
        lockSession:
          position: "before session"
          middleware: "DigiComp\\FlowSessionLock\\Http\\SessionLockRequestMiddleware"
