Neos:
  Flow:
    http:
      chain:
        preprocess:
          chain:
            lockSession:
              position: 'before getSessionCookieFromRequest'
              component: 'DigiComp\FlowSessionLock\Http\SessionLockRequestComponent'

DigiComp:
  FlowSessionLock:
    lockStoreDir: '%FLOW_PATH_DATA%Temporary/Production/SessionLocks'
    readOnlyExpressions: []
    autoRelease: true
    timeToLive: 300
